combine_control_expr = true
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
unstable_features = true
wrap_comments = true

# https://lkml.org/lkml/2020/5/29/1038
comment_width = 100
